#!/usr/bin/env bash
# install-linux-agent.sh — install a Vexor Logs shipper (vector or fluent-bit).
# Re-runnable: idempotent installs and config rewrites only.
#
# Usage:
#   install-linux-agent.sh --vexor-url https://vexor.example.com \
#                          --token <bootstrap-token> \
#                          [--agent vector|fluentbit] \
#                          [--log /var/log/foo] [--log /var/log/bar]
#
# When omitted, --log defaults to /var/log (recursive).
set -euo pipefail

AGENT="vector"
TOKEN=""
URL=""
HOST_NAME=""
LOGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --vexor-url) URL="$2"; shift 2 ;;
    --token)     TOKEN="$2"; shift 2 ;;
    --agent)     AGENT="$2"; shift 2 ;;
    --log|--logs) LOGS+=("$2"); shift 2 ;;
    --host-name) HOST_NAME="$2"; shift 2 ;;
    --help|-h)   sed -n "2,12p" "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$URL" ]]; then
  echo "ERROR: --vexor-url is required" >&2; exit 2
fi
if [[ ${#LOGS[@]} -eq 0 ]]; then
  LOGS=("/var/log")
fi

# Host label used in VictoriaLogs. Prefer the Vexor host name passed by
# the deploy (so logs match the host as Vexor knows it); fall back to the
# box's own hostname. Baked at install time.
EFFECTIVE_HOST="${HOST_NAME:-$(hostname)}"

# Extract host:port for the VictoriaLogs JSON push endpoint.
# We assume the Vexor reverse-proxy forwards /api/v1/logs/push -> VictoriaLogs.
VEXOR_HOST="$(echo "$URL" | sed -E 's#^https?://##; s#/.*##')"
echo "+ Installing $AGENT on $(hostname) shipping to $URL"

# ---- Detect package manager ------------------------------------------------
PKG=""
if   command -v dnf >/dev/null 2>&1; then PKG=dnf
elif command -v yum >/dev/null 2>&1; then PKG=yum
elif command -v apt-get >/dev/null 2>&1; then PKG=apt
fi

install_vector() {
  if command -v vector >/dev/null 2>&1; then
    echo "vector already installed: $(vector --version | head -1)"
    return
  fi
  case "$PKG" in
    dnf|yum)
      curl -1sLf 'https://repositories.timber.io/public/vector/cfg/setup/bash.rpm.sh' | sudo bash
      sudo $PKG install -y vector
      ;;
    apt)
      curl -1sLf 'https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh' | sudo bash
      sudo apt-get install -y vector
      ;;
    *)
      echo "no supported package manager — download vector manually from https://vector.dev" >&2
      exit 3
      ;;
  esac
}

install_fluentbit() {
  if command -v fluent-bit >/dev/null 2>&1; then
    echo "fluent-bit already installed: $(fluent-bit --version | head -1)"
    return
  fi
  case "$PKG" in
    dnf|yum)
      curl -fsSL https://packages.fluentbit.io/fluentbit.key | sudo tee /etc/pki/rpm-gpg/fluentbit.key >/dev/null
      sudo tee /etc/yum.repos.d/fluent-bit.repo >/dev/null <<EOF
[fluent-bit]
name=Fluent Bit
baseurl=https://packages.fluentbit.io/centos/\$releasever/\$basearch
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/fluentbit.key
enabled=1
EOF
      sudo $PKG install -y fluent-bit
      ;;
    apt)
      curl -fsSL https://packages.fluentbit.io/fluentbit.key | sudo gpg --dearmor -o /usr/share/keyrings/fluentbit.gpg
      echo "deb [signed-by=/usr/share/keyrings/fluentbit.gpg] https://packages.fluentbit.io/ubuntu/$(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/fluent-bit.list
      sudo apt-get update && sudo apt-get install -y fluent-bit
      ;;
    *) echo "no supported package manager" >&2; exit 3 ;;
  esac
}

write_vector_config() {
  sudo install -d -m 0755 /etc/vexor /etc/vector
  # Build source/file paths
  local include_lines=""
  for l in "${LOGS[@]}"; do
    include_lines="$include_lines\"$l/**/*.log\","
    [[ -f "$l" ]] && include_lines="$include_lines\"$l\","
  done
  include_lines="${include_lines%,}"
  sudo tee /etc/vexor/logs.env >/dev/null <<EOF
VEXOR_LOGS_URL=${URL}
VEXOR_LOGS_TOKEN=${TOKEN}
EOF
  sudo tee /etc/vector/vector.toml >/dev/null <<EOF
# Generated by vexor install-linux-agent.sh
data_dir = "/var/lib/vector"

[sources.files]
type    = "file"
include = [${include_lines}]
ignore_older_secs = 86400

[sources.journald]
type = "journald"
current_boot_only = true

[transforms.add_host]
type    = "remap"
inputs  = ["files", "journald"]
source  = '''
.host = "${EFFECTIVE_HOST}"
if exists(.SYSTEMD_UNIT) {
  .service = .SYSTEMD_UNIT
} else if exists(.file) {
  .service = .file
} else {
  .service = "unknown"
}
if exists(.message) {
  ._msg = del(.message)
} else if exists(.MESSAGE) {
  ._msg = .MESSAGE
} else if !exists(._msg) {
  ._msg = ""
}
'''

[sinks.vexor]
type    = "http"
inputs  = ["add_host"]
uri     = "${URL}/api/v1/logs/push?_stream_fields=host,file"
encoding.codec = "json"
framing.method = "newline_delimited"
compression = "gzip"
healthcheck.enabled = false
# Vexor servers commonly use a self-signed cert on the LAN; the ingest endpoint
# is token-authenticated. Matches the fluent-bit "tls.verify off" behaviour.
tls.verify_certificate = false
EOF
  if [[ -n "$TOKEN" ]]; then
    sudo tee -a /etc/vector/vector.toml >/dev/null <<EOF
request.headers.Authorization = "Bearer ${TOKEN}"
EOF
  fi
}

write_fluentbit_config() {
  sudo install -d -m 0755 /etc/vexor /etc/fluent-bit
  local inputs=""
  for l in "${LOGS[@]}"; do
    inputs="${inputs}
[INPUT]
    Name        tail
    Path        ${l}/*.log
    Tag         vexor.${l##*/}
    Refresh_Interval 5
"
  done
  sudo tee /etc/fluent-bit/fluent-bit.conf >/dev/null <<EOF
[SERVICE]
    Flush       5
    Log_Level   info
    Parsers_File parsers.conf
${inputs}
[FILTER]
    Name        record_modifier
    Match       *
    Record      host ${EFFECTIVE_HOST}

[OUTPUT]
    Name        http
    Match       *
    Host        ${VEXOR_HOST%:*}
    Port        $(echo "${VEXOR_HOST##*:}" | grep -E '^[0-9]+\$' || echo 443)
    URI         /api/v1/logs/push
    Format      json_lines
    tls         on
    tls.verify  off
    $( [[ -n "$TOKEN" ]] && echo "Header      Authorization Bearer ${TOKEN}" )
EOF
}

case "$AGENT" in
  vector)
    # If this host already runs the built-in Vexor shipper (vexor-vector,
    # present on Vexor server nodes), its logs are already collected — do not
    # install a conflicting second shipper.
    if systemctl list-unit-files 2>/dev/null | grep -q '^vexor-vector\.service'; then
      echo "This host already runs vexor-vector; its logs are already shipped to Vexor."
      sudo systemctl enable --now vexor-vector >/dev/null 2>&1 || true
      echo "OK: nothing to do (vexor-vector already active)."
      exit 0
    fi
    install_vector
    write_vector_config
    sudo mkdir -p /var/lib/vector
    # Ship a dedicated unit that runs vector as root with OUR config, so we do
    # not depend on the upstream package's unit name (which may be absent, or
    # run as the 'vector' user with the demo config and never read our
    # /etc/vector/vector.toml).
    VECTOR_BIN="$(command -v vector || echo /usr/bin/vector)"
    sudo tee /etc/systemd/system/vexor-log-agent.service >/dev/null <<EOF
[Unit]
Description=Vexor Log Agent (vector)
After=network-online.target
Wants=network-online.target

[Service]
User=root
Group=root
ExecStartPre=${VECTOR_BIN} validate --config-toml /etc/vector/vector.toml
ExecStart=${VECTOR_BIN} --config-toml /etc/vector/vector.toml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
    # Stop any upstream vector.service so the two don't double-ship.
    sudo systemctl disable --now vector >/dev/null 2>&1 || true
    sudo systemctl daemon-reload
    sudo systemctl enable --now vexor-log-agent
    sudo systemctl restart vexor-log-agent
    AGENT=vexor-log-agent
    ;;
  fluentbit|fluent-bit)
    install_fluentbit
    write_fluentbit_config
    sudo systemctl enable --now fluent-bit
    sudo systemctl restart fluent-bit
    ;;
  *) echo "unknown agent: $AGENT" >&2; exit 2 ;;
esac

echo "OK: $AGENT installed and started. Inspect logs with: journalctl -u $AGENT -n50"
